# Generated by Django 2.1.15 on 2020-09-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='namne',
            new_name='name',
        ),
    ]
